project:
  type: book

book:
  title: "test-website.github.io"
  author: "Ward Langeraert"
  date: "`r Sys.Date()`"
  chapters:
    - index.qmd
    - intro.qmd
    - summary.qmd
    - references.qmd

downloads: [pdf, epub]
  sidebar:
    pinned: true
    tools:
      - icon: save
        menu:
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"
          - text: ""
            url:  "#"

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



